import { Subscriber } from "@/components/data-table";

export const subscriberData: Subscriber[] = [
  {
    id: 1,
    subscriberId: "SUB-001",
    name: "John Smith",
    email: "john.smith@email.com",
    status: "Active",
    signupDate: "2024-01-15",
    source: "Website",
  },
  {
    id: 2,
    subscriberId: "SUB-002",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    status: "Active",
    signupDate: "2024-01-20",
    source: "Social Media",
  },
  {
    id: 3,
    subscriberId: "SUB-003",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    status: "Pending",
    signupDate: "2024-02-01",
    source: "Email Campaign",
  },
  {
    id: 4,
    subscriberId: "SUB-004",
    name: "Emily Davis",
    email: "emily.davis@email.com",
    status: "Active",
    signupDate: "2024-02-05",
    source: "Referral",
  },
  {
    id: 5,
    subscriberId: "SUB-005",
    name: "David Wilson",
    email: "david.wilson@email.com",
    status: "Inactive",
    signupDate: "2024-02-10",
    source: "Direct",
  },
  {
    id: 6,
    subscriberId: "SUB-006",
    name: "Lisa Anderson",
    email: "lisa.anderson@email.com",
    status: "Active",
    signupDate: "2024-02-15",
    source: "Advertisement",
  },
  {
    id: 7,
    subscriberId: "SUB-007",
    name: "Robert Taylor",
    email: "robert.taylor@email.com",
    status: "Unsubscribed",
    signupDate: "2024-02-20",
    source: "Website",
  },
  {
    id: 8,
    subscriberId: "SUB-008",
    name: "Jennifer Martinez",
    email: "jennifer.martinez@email.com",
    status: "Active",
    signupDate: "2024-02-25",
    source: "Social Media",
  },
  {
    id: 9,
    subscriberId: "SUB-009",
    name: "Christopher Lee",
    email: "christopher.lee@email.com",
    status: "Active",
    signupDate: "2024-03-01",
    source: "Email Campaign",
  },
  {
    id: 10,
    subscriberId: "SUB-010",
    name: "Amanda White",
    email: "amanda.white@email.com",
    status: "Pending",
    signupDate: "2024-03-05",
    source: "Referral",
  },
  {
    id: 11,
    subscriberId: "SUB-011",
    name: "James Garcia",
    email: "james.garcia@email.com",
    status: "Active",
    signupDate: "2024-03-10",
    source: "Direct",
  },
  {
    id: 12,
    subscriberId: "SUB-012",
    name: "Michelle Rodriguez",
    email: "michelle.rodriguez@email.com",
    status: "Active",
    signupDate: "2024-03-15",
    source: "Advertisement",
  },
  {
    id: 13,
    subscriberId: "SUB-013",
    name: "Kevin Thompson",
    email: "kevin.thompson@email.com",
    status: "Inactive",
    signupDate: "2024-03-20",
    source: "Website",
  },
  {
    id: 14,
    subscriberId: "SUB-014",
    name: "Nicole Clark",
    email: "nicole.clark@email.com",
    status: "Active",
    signupDate: "2024-03-25",
    source: "Social Media",
  },
  {
    id: 15,
    subscriberId: "SUB-015",
    name: "Daniel Lewis",
    email: "daniel.lewis@email.com",
    status: "Active",
    signupDate: "2024-04-01",
    source: "Email Campaign",
  },
  {
    id: 16,
    subscriberId: "SUB-016",
    name: "Rachel Walker",
    email: "rachel.walker@email.com",
    status: "Pending",
    signupDate: "2024-04-05",
    source: "Referral",
  },
  {
    id: 17,
    subscriberId: "SUB-017",
    name: "Mark Hall",
    email: "mark.hall@email.com",
    status: "Active",
    signupDate: "2024-04-10",
    source: "Direct",
  },
  {
    id: 18,
    subscriberId: "SUB-018",
    name: "Stephanie Allen",
    email: "stephanie.allen@email.com",
    status: "Active",
    signupDate: "2024-04-15",
    source: "Advertisement",
  },
  {
    id: 19,
    subscriberId: "SUB-019",
    name: "Brian Young",
    email: "brian.young@email.com",
    status: "Unsubscribed",
    signupDate: "2024-04-20",
    source: "Website",
  },
  {
    id: 20,
    subscriberId: "SUB-020",
    name: "Laura King",
    email: "laura.king@email.com",
    status: "Active",
    signupDate: "2024-04-25",
    source: "Social Media",
  },
  {
    id: 21,
    subscriberId: "SUB-021",
    name: "Gregory Wright",
    email: "gregory.wright@email.com",
    status: "Active",
    signupDate: "2024-05-01",
    source: "Email Campaign",
  },
  {
    id: 22,
    subscriberId: "SUB-022",
    name: "Kimberly Lopez",
    email: "kimberly.lopez@email.com",
    status: "Active",
    signupDate: "2024-05-05",
    source: "Referral",
  },
  {
    id: 23,
    subscriberId: "SUB-023",
    name: "Anthony Hill",
    email: "anthony.hill@email.com",
    status: "Inactive",
    signupDate: "2024-05-10",
    source: "Direct",
  },
  {
    id: 24,
    subscriberId: "SUB-024",
    name: "Melissa Scott",
    email: "melissa.scott@email.com",
    status: "Active",
    signupDate: "2024-05-15",
    source: "Advertisement",
  },
  {
    id: 25,
    subscriberId: "SUB-025",
    name: "Steven Green",
    email: "steven.green@email.com",
    status: "Active",
    signupDate: "2024-05-20",
    source: "Website",
  },
];
